ARG NODE_TAG

FROM node:${NODE_TAG}

WORKDIR /app

# RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null \
#     && echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list \
#     && apt update \
#     && apt-get install yarn -y \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/* \
#     && rm -rf /tmp/downloaded_packages

COPY package*.json ./

RUN npm install

ARG ANGULAR_CLI_VERSION

RUN RUN npm install -g @angular/cli@${ANGULAR_CLI_VERSION}

COPY . .

CMD ["npm", "run", "start"]
